sonar.projectKey=secureshield
sonar.projectName=SecureShield
sonar.projectVersion=1.0

sonar.sources=app/src
sonar.tests=app/tests
sonar.language=js
sonar.sourceEncoding=UTF-8

# Coverage report location
sonar.javascript.lcov.reportPaths=app/coverage/lcov.info

# Exclusions
sonar.exclusions=**/node_modules/**,**/coverage/**

# Quality Gate
sonar.qualitygate.wait=true
